# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Capture the why behind your code changes"
  homepage "https://github.com/partio-io/cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "d505d5e3c4fb96f9b3a1302448939e4c9c0187a398b68cee997e061d2c1267d1"

      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "05ba695dfeb58aa3eeaeef377a55c83b4c1a19606b2b17ec7000976283000bfd"

      def install
        bin.install "partio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_amd64.tar.gz"
      sha256 "3c1d4a17d1cf70d8f163f728aec38e0e830365c0b81a591e08fa51cb4e7ee6c1"
      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_arm64.tar.gz"
      sha256 "aac99e8db8439a60c77a92ed83431668310bf5a5689ba9711142c309ce42dc5d"
      def install
        bin.install "partio"
      end
    end
  end

  test do
    system "#{bin}/partio", "version"
  end
end
