# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Capture the why behind your code changes"
  homepage "https://github.com/partio-io/cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "734a2ef297ff5338d94354ca4fc13b24efb094338e25dd02e18333708c1802bb"

      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "2ae917f5cc9051f9a8e4e864f264633df9f91520c5d20be946896869d566a15d"

      def install
        bin.install "partio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_amd64.tar.gz"
      sha256 "a2c0065a29974db82a7826469b1b42770e2f90add41330aac015e246338b6e9c"
      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_arm64.tar.gz"
      sha256 "ee108f0f7d6d8d2b5091d8d4f5e9cd8acc9014123ab1f974882858be62d3315c"
      def install
        bin.install "partio"
      end
    end
  end

  test do
    system "#{bin}/partio", "version"
  end
end
