# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Partio < Formula
  desc "Capture the why behind your code changes"
  homepage "https://github.com/partio-io/cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/partio-io/cli/releases/download/v0.0.2/partio_0.0.2_darwin_amd64.tar.gz"
      sha256 "1b51395bd17a79a06705dc577b16306534625ae0228dca36f3eab06008e95f7b"

      define_method(:install) do
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/partio-io/cli/releases/download/v0.0.2/partio_0.0.2_darwin_arm64.tar.gz"
      sha256 "9b2b58dfa166c9530cad551e403d69ebcf721bccfb415950ab5db419d5586b48"

      define_method(:install) do
        bin.install "partio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.2/partio_0.0.2_linux_amd64.tar.gz"
      sha256 "37a1f9de2b36bae90a23a700d1d26fbd068021926aff8d607907d9686d9c9685"
      define_method(:install) do
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.2/partio_0.0.2_linux_arm64.tar.gz"
      sha256 "c1b2c95018d90261afde8fbea7cd8816f1234097befe6e3bfd50e25142801061"
      define_method(:install) do
        bin.install "partio"
      end
    end
  end

  test do
    system "#{bin}/partio", "version"
  end
end
