# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Partio < Formula
  desc "Capture the why behind your code changes"
  homepage "https://github.com/partio-io/cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/partio_0.0.1_darwin_amd64.tar.gz"
      sha256 "2c4bd374f7676a7875478501b1b3b916634d8696eddaf9180049120d063fa89c"

      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/partio_0.0.1_darwin_arm64.tar.gz"
      sha256 "179c12560b2d9b465eda7878dc0031d7beef206d2339eb158554ca3d9ec52388"

      def install
        bin.install "partio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/partio_0.0.1_linux_amd64.tar.gz"
      sha256 "4a66c224c079b97213d4b1a87229bf3a303ca9f16b9d06512402a1f866244679"
      def install
        bin.install "partio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/partio-io/cli/releases/download/v0.0.1/partio_0.0.1_linux_arm64.tar.gz"
      sha256 "e2883f083f2eee0190b83b43553457db15322133c2eb9af6c1d3c2221cd625ee"
      def install
        bin.install "partio"
      end
    end
  end

  test do
    system "#{bin}/partio", "version"
  end
end
